name: TestReleaseTools
version: 0.1
date: 01/03/2016
description: Test package for ReleaseTools

authors:
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://fingolfin.github.io/TestReleaseTools/
readme: https://fingolfin.github.io/TestReleaseTools/README.md
packageinfo: https://fingolfin.github.io/TestReleaseTools/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/fingolfin/TestReleaseTools/releases/download/v0.1/TestReleaseTools-0.1.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
